-- 002: Add denormalized count columns to high-traffic tables

BEGIN;

-- galgame
ALTER TABLE galgame ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame ADD COLUMN IF NOT EXISTS favorite_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame ADD COLUMN IF NOT EXISTS resource_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame ADD COLUMN IF NOT EXISTS comment_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame ADD COLUMN IF NOT EXISTS contributor_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame ADD COLUMN IF NOT EXISTS rating_count INT NOT NULL DEFAULT 0;

-- topic
ALTER TABLE topic ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic ADD COLUMN IF NOT EXISTS dislike_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic ADD COLUMN IF NOT EXISTS reply_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic ADD COLUMN IF NOT EXISTS comment_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic ADD COLUMN IF NOT EXISTS favorite_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic ADD COLUMN IF NOT EXISTS upvote_count INT NOT NULL DEFAULT 0;

-- topic_reply
ALTER TABLE topic_reply ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic_reply ADD COLUMN IF NOT EXISTS dislike_count INT NOT NULL DEFAULT 0;
ALTER TABLE topic_reply ADD COLUMN IF NOT EXISTS comment_count INT NOT NULL DEFAULT 0;

-- galgame_resource
ALTER TABLE galgame_resource ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;

-- galgame_comment
ALTER TABLE galgame_comment ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;

-- galgame_rating
ALTER TABLE galgame_rating ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame_rating ADD COLUMN IF NOT EXISTS comment_count INT NOT NULL DEFAULT 0;

-- galgame_website
ALTER TABLE galgame_website ADD COLUMN IF NOT EXISTS like_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame_website ADD COLUMN IF NOT EXISTS favorite_count INT NOT NULL DEFAULT 0;
ALTER TABLE galgame_website ADD COLUMN IF NOT EXISTS comment_count INT NOT NULL DEFAULT 0;

-- topic_poll_option
ALTER TABLE topic_poll_option ADD COLUMN IF NOT EXISTS vote_count INT NOT NULL DEFAULT 0;

COMMIT;
