DROP TRIGGER IF EXISTS trg_feed_topic ON topic;
DROP TRIGGER IF EXISTS trg_feed_topic_reply ON topic_reply;
DROP TRIGGER IF EXISTS trg_feed_topic_comment ON topic_comment;
DROP TRIGGER IF EXISTS trg_feed_topic_upvote ON topic_upvote;
DROP TRIGGER IF EXISTS trg_feed_galgame ON galgame;
DROP TRIGGER IF EXISTS trg_feed_galgame_comment ON galgame_comment;
DROP TRIGGER IF EXISTS trg_feed_galgame_resource ON galgame_resource;
DROP TRIGGER IF EXISTS trg_feed_galgame_activity ON galgame_activity;
DROP TRIGGER IF EXISTS trg_feed_galgame_rating ON galgame_rating;
DROP TRIGGER IF EXISTS trg_feed_galgame_rating_comment ON galgame_rating_comment;
DROP TRIGGER IF EXISTS trg_feed_galgame_website ON galgame_website;
DROP TRIGGER IF EXISTS trg_feed_galgame_website_comment ON galgame_website_comment;
DROP TRIGGER IF EXISTS trg_feed_galgame_toolset ON galgame_toolset;
DROP TRIGGER IF EXISTS trg_feed_galgame_toolset_resource ON galgame_toolset_resource;
DROP TRIGGER IF EXISTS trg_feed_galgame_toolset_comment ON galgame_toolset_comment;
DROP TRIGGER IF EXISTS trg_feed_todo ON todo;
DROP TRIGGER IF EXISTS trg_feed_update_log ON update_log;
DROP TRIGGER IF EXISTS trg_feed_message ON message;

DROP FUNCTION IF EXISTS feed_sync_topic();
DROP FUNCTION IF EXISTS feed_sync_topic_reply();
DROP FUNCTION IF EXISTS feed_sync_topic_comment();
DROP FUNCTION IF EXISTS feed_sync_topic_upvote();
DROP FUNCTION IF EXISTS feed_sync_galgame();
DROP FUNCTION IF EXISTS feed_sync_galgame_comment();
DROP FUNCTION IF EXISTS feed_sync_galgame_resource();
DROP FUNCTION IF EXISTS feed_sync_galgame_activity();
DROP FUNCTION IF EXISTS feed_sync_galgame_rating();
DROP FUNCTION IF EXISTS feed_sync_galgame_rating_comment();
DROP FUNCTION IF EXISTS feed_sync_galgame_website();
DROP FUNCTION IF EXISTS feed_sync_galgame_website_comment();
DROP FUNCTION IF EXISTS feed_sync_galgame_toolset();
DROP FUNCTION IF EXISTS feed_sync_galgame_toolset_resource();
DROP FUNCTION IF EXISTS feed_sync_galgame_toolset_comment();
DROP FUNCTION IF EXISTS feed_sync_todo();
DROP FUNCTION IF EXISTS feed_sync_update_log();
DROP FUNCTION IF EXISTS feed_sync_message();
DROP FUNCTION IF EXISTS feed_upsert(text, int, int, int, text, text, boolean, timestamptz);
DROP FUNCTION IF EXISTS feed_delete(text, int);

DROP TABLE IF EXISTS feed_activity;
