-- Recreate the (empty) legacy report table for rollback symmetry. The original
-- data is not restored — it was discarded on purpose.
CREATE TABLE IF NOT EXISTS report (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reason character varying(1007) NOT NULL,
    type text DEFAULT ''::text NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    created timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated timestamp(3) without time zone NOT NULL
);
