-- Galgame comment migration onto the community primitive (charter step 03).
-- Additive and safe to deploy BEFORE the cutover: with the feature flag off
-- (KUN_GALGAME_COMMENTS_COMMUNITY unset) both tables sit idle.

-- galgame_comment_community_map: old galgame_comment id -> its migrated
-- community (thread, post), for deep-link / old-anchor continuity (charter
-- ruling 9). ALSO created by the infra import tool (step 02) with the IDENTICAL
-- CREATE TABLE IF NOT EXISTS DDL, so adopting it here is idempotent whichever
-- side runs first. NOT back-filled here: the map is populated by the import tool
-- at cutover.
CREATE TABLE IF NOT EXISTS galgame_comment_community_map (
  old_comment_id int    PRIMARY KEY,
  thread_id      bigint NOT NULL,
  post_id        bigint NOT NULL,
  galgame_id     int    NOT NULL
);

-- galgame_post_like: kungal's LOCAL like row for a community post (charter
-- ruling 8). The community PostView carries no reaction count, so the display
-- count + "我赞过" flag live here; the BFF drives this table from the primitive's
-- authoritative reaction toggle (added/removed), while the community reaction
-- itself feeds the trust engine. Distinct from the frozen legacy
-- galgame_comment_like (which FK-pins old comment ids and is kept as-is).
--
-- NOT back-filled here. The existing likes are copied over at cutover (step 05)
-- by a single JOIN against the map table (both tables live in the forum DB for
-- exactly this reason):
--   INSERT INTO galgame_post_like (post_id, user_id, created)
--   SELECT m.post_id, l.user_id, l.created
--   FROM galgame_comment_like l
--   JOIN galgame_comment_community_map m ON m.old_comment_id = l.galgame_comment_id
--   ON CONFLICT (post_id, user_id) DO NOTHING;
CREATE TABLE IF NOT EXISTS galgame_post_like (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint      NOT NULL,
  user_id int         NOT NULL,
  created timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_galgame_post_like UNIQUE (post_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_galgame_post_like_post ON galgame_post_like (post_id);
